create or replace NONEDITIONABLE procedure sp_delete_tables

AUTHID CURRENT_USER
as
--variables

begin

    execute IMMEDIATE 'DROP TABLE REPUESTOS_Y_MANTENIMIENTOS';
    execute IMMEDIATE 'DROP TABLE SERVICIOS_Y_MANTENIMIENTOS';
    execute IMMEDIATE 'DROP TABLE FOTOS';
    execute IMMEDIATE 'DROP TABLE DETALLE_FACTURA';
    execute IMMEDIATE 'DROP TABLE MANTENIMIENTOS';
    execute IMMEDIATE 'DROP TABLE REPUESTOS';
    execute IMMEDIATE 'DROP TABLE VEHICULOS';
    execute IMMEDIATE 'DROP TABLE SERVICIOS';
    execute IMMEDIATE 'DROP TABLE MECANICOS';
    execute IMMEDIATE 'DROP TABLE MARCAS';
    execute IMMEDIATE 'DROP TABLE FACTURAS';
    execute IMMEDIATE 'DROP TABLE CLIENTES';

end;